
title: Xutong Wang
url: 'http://suzanna0902.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Xutong Wang
tagline: Epidemiology/Statistics/<br />Computational Biology 
pic: bio-photo.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: wangxutong@utexas.edu 
website: suzanna0902.github.io #do not add http://
linkedin: Xutong Wang
github: suzanna0902

#Update all the sections by editing the files inside _includes folder.
